Domain:                       alza.sk
Created:                      2004-05-21
Valid Until:                  2025-04-24
Updated:                      2024-03-21
Domain Status:                ok
Nameserver:                   beau.ns.cloudflare.com
Nameserver:                   gigi.ns.cloudflare.com

Domain registrant:            A24C-154952
Name:                         Alza.cz a.s.
Organization:                 Alza.cz a.s.
Organization ID:              27082440
Street:                       Jankovcova 1522/53
City:                         Praha 7
Postal Code:                  17000
Country Code:                 CZ
Authorised Registrar:         ACTI-0024
Created:                      2021-06-28
Updated:                      2023-09-15

Registrar:                    ACTI-0024
Name:                         ACTIVE 24, s.r.o.
Organization:                 ACTIVE 24, s.r.o.
Organization ID:              25115804
Phone:                        +421.244460639
Email:                        registrace@domeny.cz
Street:                       Sokolovska 394/17
City:                         Praha
Postal Code:                  18600
Country Code:                 CZ
Created:                      2017-09-14
Updated:                      2024-10-10

Administrative Contact:       A24C-154952
Name:                         Alza.cz a.s.
Organization:                 Alza.cz a.s.
Organization ID:              27082440
Street:                       Jankovcova 1522/53
City:                         Praha 7
Postal Code:                  17000
Country Code:                 CZ
Created:                      2021-06-28
Updated:                      2023-09-15

Technical Contact:            ACTI-0024
Name:                         ACTIVE 24, s.r.o.
Organization:                 ACTIVE 24, s.r.o.
Organization ID:              25115804
Phone:                        +421.244460639
Email:                        registrace@domeny.cz
Street:                       Sokolovska 394/17
City:                         Praha
Postal Code:                  18600
Country Code:                 CZ
Created:                      2017-09-14
Updated:                      2024-10-10
