Domain:                       google.sk
Created:                      2003-07-24
Valid Until:                  2025-07-24
Updated:                      2024-06-22
Domain Status:                clientTransferProhibited, clientUpdateProhibited, clientDeleteProhibited
Nameserver:                   ns1.google.com
Nameserver:                   ns2.google.com
Nameserver:                   ns3.google.com
Nameserver:                   ns4.google.com

Domain registrant:            mmr-170347
Name:                         Domain Administrator
Organization:                 Google Ireland Holdings Unlimited Company
Organization ID:              369511
Phone:                        +353.14361000
Email:                        dns-admin@google.com
Street:                       70 Sir John Rogerson's Quay
City:                         Dublin
Postal Code:                  2
Country Code:                 IE
Authorised Registrar:         MARK-0292
Created:                      2019-06-07
Updated:                      2019-06-07

Registrar:                    MARK-0292
Name:                         MarkMonitor International Limited
Organization:                 MarkMonitor International Limited
Organization ID:              4847541
Phone:                        +1.2083895740
Email:                        registry.admin@markmonitor.com
Street:                       12 New Fetter Lane
City:                         London
Postal Code:                  EC4A 1JP
Country Code:                 UK
Created:                      2018-06-27
Updated:                      2024-09-30

Administrative Contact:       mmr-170347
Name:                         Domain Administrator
Organization:                 Google Ireland Holdings Unlimited Company
Organization ID:              369511
Phone:                        +353.14361000
Email:                        dns-admin@google.com
Street:                       70 Sir John Rogerson's Quay
City:                         Dublin
Postal Code:                  2
Country Code:                 IE
Created:                      2019-06-07
Updated:                      2019-06-07

Technical Contact:            mmr-170347
Name:                         Domain Administrator
Organization:                 Google Ireland Holdings Unlimited Company
Organization ID:              369511
Phone:                        +353.14361000
Email:                        dns-admin@google.com
Street:                       70 Sir John Rogerson's Quay
City:                         Dublin
Postal Code:                  2
Country Code:                 IE
Created:                      2019-06-07
Updated:                      2019-06-07
