
   Rights restricted by copyright. See
   http://www.dot.tk/en/pageF00.html

   Domain name:
      ZCORE.TK 

   Organisation:
      Korol
      Korol
      Kharkiv, str. Mira 34
      61007  Kharkiv 
      Kharkivs'ka Oblast'
      Ukraine
      Phone: +380 67-2124222
      Fax: +380 67-2124222
      E-mail: korol1979a@rambler.ru

   Domain Nameservers:
      NS02.FREENOM.COM
      NS01.FREENOM.COM
      NS03.FREENOM.COM
      NS04.FREENOM.COM

   Domain registered: 11/29/2016
   Record will expire on: 01/03/2022
   Record maintained by: Dot TK Domain Registry
