% Request from 1.1.1.1
% This is the Ukrainian Whois query server #B.
% The Whois is subject to Terms of use
% See https://hostmaster.ua/services/
%
% IN THE PROCESS OF DELEGATION OF A DOMAIN NAME,
% THE REGISTRANT IS AN ENTITY WHO USES AND MANAGES A CERTAIN DOMAIN NAME,
% AND THE REGISTRAR IS A BUSINESS ENTITY THAT PROVIDES THE REGISTRANT
% WITH THE SERVICES NECESSARY FOR THE TECHNICAL MAINTENANCE OF THE REGISTRATION AND OPERATION OF THE DOMAIN NAME.
% FOR INFORMATION ABOUT THE REGISTRANT OF THE DOMAIN NAME, YOU SHOULD CONTACT THE REGISTRAR.

domain:           google.ua
dom-public:       NO
license:          82319
mnt-by:           ua.markmonitor
nserver:          ns1.google.com
nserver:          ns2.google.com
nserver:          ns3.google.com
nserver:          ns4.google.com
status:           clientDeleteProhibited
status:           clientTransferProhibited
status:           clientUpdateProhibited
created:          2011-07-21 18:03:50+03
modified:         2022-06-19 12:24:23+03
expires:          2023-07-21 18:03:50+03
source:           UAEPP

% Registrar:
% ==========
registrar:        ua.markmonitor
organization:     MarkMonitor Inc.
organization-loc: MarkMonitor Inc.
url:              http://markmonitor.com
city:             Meridian, Idaho
country:          US
abuse-email:      abusecomplaints@markmonitor.com
abuse-postal:     US 83642 Meridian, Idaho 2150 S. Bonito Way, Suite 150
source:           UAEPP

% Registrant:
% ===========
person:           n/a
person-loc:       Inc. Google
organization-loc: Google Inc.
e-mail:           dns-admin@google.com
address:          n/a
address-loc:      Amphitheatre Parkway, 1600
address-loc:      Mountain View
postal-code-loc:  94043
country-loc:      US
phone:            +1.6502530000
fax:              +1.6506188571
mnt-by:           ua.markmonitor
status:           ok
status:           linked
created:          2017-07-21 23:55:01+03
source:           UAEPP



% Query time:     7 msec
