% Request from 1.1.1.1
% This is the Ukrainian Whois query server #F.
% The Whois is subject to Terms of use
% See https://hostmaster.ua/services/
%
% IN THE PROCESS OF DELEGATION OF A DOMAIN NAME,
% THE REGISTRANT IS AN ENTITY WHO USES AND MANAGES A CERTAIN DOMAIN NAME,
% AND THE REGISTRAR IS A BUSINESS ENTITY THAT PROVIDES THE REGISTRANT
% WITH THE SERVICES NECESSARY FOR THE TECHNICAL MAINTENANCE OF THE REGISTRATION AND OPERATION OF THE DOMAIN NAME.
% FOR INFORMATION ABOUT THE REGISTRANT OF THE DOMAIN NAME, YOU SHOULD CONTACT THE REGISTRAR.

domain:           nic.ua
dom-public:       NO
license:          82263
mnt-by:           ua.nic
nserver:          ns1.uadns.com
nserver:          ns2.uadns.com
status:           clientDeleteProhibited
status:           clientTransferProhibited
created:          2007-10-04 13:40:19+03
modified:         2021-12-27 14:13:20+02
expires:          2024-10-04 13:40:18+03
source:           UAEPP

% Registrar:
% ==========
registrar:        ua.nic
organization:     NIC.UA LLC
organization-loc: ТОВ "НІК.ЮЕЙ"
url:              http://nic.ua
city:             Dnipro
country:          UA
abuse-email:      abuse@nic.ua
abuse-phone:      +380445933222
abuse-postal:     Ukraine 49000 Dnipro PO/BOX 80
abuse-postal-loc: Україна 49000 Дніпро а/с 80
source:           UAEPP

% Registrant:
% ===========
person:           NIC.UA LLC
person-loc:       ТОВ "НІК.ЮЕЙ"
organization:     NIC.UA LLC
organization-loc: ТОВ "НІК.ЮЕЙ"
e-mail:           uanic@nic.ua
address:          Plehanova 18 512
address:          Dnipro
postal-code:      49000
country:          UA
address-loc:      Plehanova 18 512
address-loc:      Dnipro
postal-code-loc:  49000
country-loc:      UA
phone:            +380.445933222
fax:              +380.445937569
mnt-by:           ua.nic
status:           ok
status:           linked
created:          2014-03-31 17:30:46+03
modified:         2019-08-31 22:09:32+03
source:           UAEPP


% Administrative Contacts:
% =======================
person:           NIC.UA LLC
person-loc:       ТОВ "НІК.ЮЕЙ"
organization:     NIC.UA LLC
organization-loc: ТОВ "НІК.ЮЕЙ"
e-mail:           uanic@nic.ua
address:          Plehanova 18 512
address:          Dnipro
postal-code:      49000
country:          UA
address-loc:      Plehanova 18 512
address-loc:      Dnipro
postal-code-loc:  49000
country-loc:      UA
phone:            +380.445933222
fax:              +380.445937569
mnt-by:           ua.nic
status:           ok
status:           linked
created:          2014-03-31 17:08:46+03
modified:         2019-08-31 22:07:53+03
source:           UAEPP


% Technical Contacts:
% ===================
person:           NIC.UA LLC
person-loc:       ТОВ "НІК.ЮЕЙ"
organization:     NIC.UA LLC
organization-loc: ТОВ "НІК.ЮЕЙ"
e-mail:           support@nic.ua
address:          Kniazia Volodymyra Velykoho str. 18 512
address:          Dnipro
postal-code:      49000
country:          UA
address-loc:      вул. Князя Володимира Великого 18 512
address-loc:      Дніпро
postal-code-loc:  49000
country-loc:      UA
phone:            +380.442329962
fax:              +380.445937569
mnt-by:           ua.nic
status:           ok
status:           linked
created:          2003-01-08 00:00:00+02
modified:         2019-08-31 22:13:21+03
source:           UAEPP



% Query time:     4 msec
